name: Deploy project to our server

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.zobayerdev.top
          username: zobayer@zobayerdev.top
          password: "UEU2BJCN2OZD"
          protocol: ftps
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/build/**
            **/.dart_tool/**
          timeout: 60000
